name: 'Deploy to Heroku' # set whatever name you want to your github job
on: 
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout
        run: echo ${{ secrets.FIREBASE_CONFIG }} | base64 -d > src/firebase/firebase-config.js
        
      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: jctaveras/heroku-deploy@v1.0.0
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile: 'Dockerfile'
          dockerfile_path: ''
          options: ''
          formation: ''
